// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cphappqwzaexecsajeeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaGFwcHF3emFleGVjc2FqZWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mzg4NjcsImV4cCI6MjA2NzAxNDg2N30.Ignmn1VfG8Tfp9U3F1y7TzvJSUAjV13X7c8kY8RWjXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});